<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);CA1515;CA1303;CA1873;CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Caesar/Caesar.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

</Project>
