<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <NoWarn>$(NoWarn);CA1707;CA2007;CA1861;CA1515;CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Caesar/Caesar.csproj" />
    <ProjectReference Include="../Caesar.Tests.Fixtures/Caesar.Tests.Fixtures.csproj" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Moq" />
  </ItemGroup>

</Project>
